### ISSUE TITLE
Plugin broken / Functionality included

### ISSUE THREAD

**Issue by BrianHenryIE** [anonymousguyx/ai1wpm-excluder#3]
Hey,

Just a note to say thanks for the plugin, I got great use out of it. I ran an export though last week and the files weren't being excluded. I tried to troubleshoot (I had an earlier PR here) but it turns out AIO Export has its own file excluder built in now.

**Comment by anonymousguyx** [comment]
Hi Brain, 
You can get an updated version from this link: https://wordpress.org/plugins/aio-files-excluder/

In FREE version of All in One WP Migration, there is no option to exclude folders and files. They've added it only in their paid extensions.

**Comment by designsbygucci** [comment]
I have the same problem since updating to the newest wordpress version 5.4 I believe. I downloaded the new plugin (from the link posted) prior to seeing this thread and still not excluding any folders. 

My server keeps crashing due to it filling up the whole hard drive, so I turned off backups for now hoping there will be a fix for this. 

edit: I also have paid extension for ALL in One, however I don't see a way to exclude folders with the automated backups to my onedrive?
